# Generated by Django 3.1.5 on 2021-03-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_name', models.CharField(max_length=128)),
                ('archive_name', models.CharField(max_length=128)),
                ('stream_song_name', models.CharField(blank=True, max_length=128)),
                ('stream_song_url', models.URLField(blank=True)),
                ('share_link', models.URLField(blank=True)),
                ('share_link_passcode', models.CharField(blank=True, max_length=4)),
                ('adam_id', models.CharField(blank=True, max_length=64)),
                ('posted', models.BooleanField(default=False)),
                ('post_url', models.URLField(blank=True)),
            ],
        ),
    ]
