# Generated by Django 3.1.5 on 2021-03-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
