# Generated by Django 3.1.5 on 2021-03-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0002_auto_20210317_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='archive_size',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
