# Generated by Django 3.1.5 on 2021-03-18 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0003_release_archive_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
