# Generated by Django 3.2.4 on 2021-06-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0005_auto_20210331_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('passcode', models.CharField(blank=True, max_length=4)),
                ('original_poster', models.CharField(blank=True, max_length=128)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postmaker.release')),
            ],
        ),
    ]
