# Generated by Django 3.2.4 on 2021-06-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0006_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
