# Generated by Django 3.2.4 on 2021-06-07 02:33

from django.db import migrations

def move_link_to_seperate_model(apps, schema_editor):

    Release = apps.get_model('postmaker', 'Release')
    Link = apps.get_model('postmaker', 'Link')
    for release in Release.objects.all():
        if release.share_link:
            link, created = Link.objects.get_or_create(
                url=release.share_link,
                passcode=release.share_link_passcode,
                release=release
            )

class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0007_alter_link_url'),
    ]

    operations = [
        migrations.RunPython(move_link_to_seperate_model),
    ]
