# Generated by Django 3.2.4 on 2021-06-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0008_auto_20210606_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('collection_name', models.CharField(max_length=200)),
                ('artwork_url', models.URLField(default='https://a.radikal.ru/a41/2104/ec/b998218537aa.png', max_length=300)),
                ('genre_name', models.CharField(blank=True, default='Unknown', max_length=32)),
                ('release_date', models.DateField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('lq_stream_url', models.URLField(blank=True)),
                ('archive_size', models.IntegerField(blank=True, default=0)),
                ('rip_source', models.CharField(choices=[('cd', 'CD'), ('web', 'Web'), ('vinyl', 'Vinyl'), ('unknown', 'Unknown')], default='unknown', max_length=7)),
                ('hidden_content', models.CharField(blank=True, max_length=200)),
                ('miscellaneous', models.JSONField(blank=True, default=list)),
                ('tracks', models.JSONField(blank=True, default=list)),
                ('download_links', models.JSONField(blank=True, default=list)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='release',
            name='autopost_alert',
            field=models.TextField(blank=True),
        ),
    ]
