# Generated by Django 3.2.4 on 2021-06-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0009_auto_20210615_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='encode',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='release',
            name='lang',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='release',
            name='rip_source',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
