# Generated by Django 3.2.4 on 2021-06-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0011_rename_encode_release_coding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
