# Generated by Django 3.2.4 on 2021-06-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0012_alter_release_release_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='share_link',
        ),
        migrations.RemoveField(
            model_name='release',
            name='share_link_passcode',
        ),
    ]
