# Generated by Django 3.2.4 on 2022-02-17 07:48

from django.db import migrations

def duplicate_minos_album_to_postmaker(apps, schema_editor):
    AlbumMinos = apps.get_model('minos', 'Album')
    AlbumPostmaker = apps.get_model('postmaker', 'Album')

    for album_minos in AlbumMinos.objects.values():
        AlbumPostmaker.objects.get_or_create(
            **album_minos
        )

class Migration(migrations.Migration):

    dependencies = [
        ('postmaker', '0014_auto_20220217_0247'),
    ]

    operations = [
        migrations.RunPython(duplicate_minos_album_to_postmaker),
    ]
