# Generated by Django 3.1.5 on 2021-04-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='original_poster',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
