# Generated by Django 3.1.5 on 2021-04-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0002_link_original_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='adam_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.URLField(default='https://a.radikal.ru/a41/2104/ec/b998218537aa.png'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(default='Unknown', max_length=32),
        ),
    ]
