# Generated by Django 3.1.5 on 2021-04-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0003_auto_20210414_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='archive_name',
            field=models.CharField(default='N/A', max_length=256),
        ),
    ]
