# Generated by Django 3.1.5 on 2021-01-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daybook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('referer', models.URLField()),
                ('origin', models.GenericIPAddressField()),
                ('country', models.CharField(max_length=3)),
                ('user_agent', models.CharField(max_length=255)),
                ('destination', models.URLField()),
            ],
            options={
                'unique_together': {('time', 'origin')},
            },
        ),
    ]
