# Generated by Django 3.1.5 on 2021-01-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daybook',
            old_name='identifier',
            new_name='referer',
        ),
    ]
