# Generated by Django 3.2.4 on 2021-06-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daybook',
            options={'ordering': ['-time']},
        ),
    ]
