# Generated by Django 3.2.4 on 2021-06-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsca', '0002_alter_daybook_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daybook',
            new_name='LinkClickedEntry',
        ),
    ]
