# Generated by Django 3.1.5 on 2021-01-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsca', '0002_auto_20210128_0846'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daybook',
            unique_together={('time', 'origin')},
        ),
    ]
